const { expect } = require('chai');
const { anyValue } = require('@nomicfoundation/hardhat-chai-matchers/withArgs');

describe('TokenAnalyzerEvidenceAnchor', function () {
  const hash = `0x${'11'.repeat(32)}`;
  const asset = `0x${'22'.repeat(32)}`;
  async function deploy() { const [owner, attestor, other] = await ethers.getSigners(); const Factory = await ethers.getContractFactory('TokenAnalyzerEvidenceAnchor'); return { owner, attestor, other, anchor: await Factory.deploy(attestor.address) }; }
  it('anchors exact evidence and exposes it permissionlessly', async function () { const { anchor, attestor } = await deploy(); const tx = await anchor.connect(attestor).anchorEvidence(hash, asset, 1); await expect(tx).to.emit(anchor, 'EvidenceAnchored').withArgs(hash, asset, 1, attestor.address, anyValue); expect(await anchor.isAnchored(hash)).eq(true); const record = await anchor.getEvidence(hash); expect(record[0]).eq(asset); expect(record[1]).eq(1); expect(record[2]).gt(0); expect(record[3]).eq(attestor.address); expect(record[4]).eq(true); });
  it('rejects unauthorized, zero and duplicate writes', async function () { const { anchor, attestor, other } = await deploy(); await expect(anchor.connect(other).anchorEvidence(hash, asset, 1)).to.be.revertedWithCustomError(anchor, 'Unauthorized'); await expect(anchor.connect(attestor).anchorEvidence(ethers.ZeroHash, asset, 1)).to.be.revertedWithCustomError(anchor, 'ZeroEvidenceHash'); await expect(anchor.connect(attestor).anchorEvidence(hash, ethers.ZeroHash, 1)).to.be.revertedWithCustomError(anchor, 'ZeroAssetKey'); await expect(anchor.connect(attestor).anchorEvidence(hash, asset, 0)).to.be.revertedWithCustomError(anchor, 'ZeroSchemaVersion'); await anchor.connect(attestor).anchorEvidence(hash, asset, 1); await expect(anchor.connect(attestor).anchorEvidence(hash, asset, 1)).to.be.revertedWithCustomError(anchor, 'EvidenceAlreadyAnchored'); });
  it('rotates attestor only for owner and preserves old evidence', async function () { const { anchor, owner, attestor, other } = await deploy(); await anchor.connect(attestor).anchorEvidence(hash, asset, 1); await expect(anchor.connect(other).setAttestor(other.address)).to.be.revertedWithCustomError(anchor, 'Unauthorized'); await expect(anchor.connect(owner).setAttestor(ethers.ZeroAddress)).to.be.revertedWithCustomError(anchor, 'ZeroAddress'); await expect(anchor.connect(owner).setAttestor(other.address)).to.emit(anchor, 'AttestorUpdated'); expect((await anchor.getEvidence(hash))[4]).eq(true); });
});
